package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"runtime"
	"strings"

	"github.com/forensichub/agent/internal/offline"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lmsgprefix)
	log.SetPrefix("[offline-agent] ")

	// Parse CLI flags.
	mode := detectMode()
	for _, arg := range os.Args[1:] {
		switch strings.ToLower(arg) {
		case "--http":
			mode = "http"
		case "--cli":
			mode = "cli"
		case "--help", "-h":
			printUsage()
			return
		}
	}

	// Load bundle manifest from bundle.json (same directory as binary).
	manifest, err := offline.LoadManifest()
	if err != nil {
		fmt.Fprintf(os.Stderr, "\n[!] Cannot load bundle: %v\n", err)
		fmt.Fprintf(os.Stderr, "    Make sure bundle.json and the tools/ directory are present\n")
		fmt.Fprintf(os.Stderr, "    next to this binary.\n\n")
		os.Exit(1)
	}

	runner := offline.NewRunner()

	switch mode {
	case "http":
		runHTTPMode(manifest, runner)
	default:
		runCLIMode(manifest, runner)
	}
}

// runHTTPMode starts the embedded HTTP server and opens the browser.
func runHTTPMode(manifest *offline.BundleManifest, runner *offline.Runner) {
	port := offline.PickPort()
	url := fmt.Sprintf("http://localhost:%d", port)

	fmt.Printf("\n")
	fmt.Printf("  ForensicHub Offline Agent\n")
	fmt.Printf("  Bundle : %s\n", manifest.Name)
	fmt.Printf("  UI     : %s\n", url)
	fmt.Printf("\n")

	if runtime.GOOS == "windows" {
		fmt.Println("  Opening browser…")
	} else if display := os.Getenv("DISPLAY"); display != "" || os.Getenv("WAYLAND_DISPLAY") != "" {
		fmt.Println("  Opening browser…")
	} else {
		fmt.Println("  SSH tunnel (run on your machine):")
		fmt.Printf("    ssh -L %d:localhost:%d user@<victim-ip>\n", port, port)
		fmt.Printf("  Then open: %s\n", url)
	}
	fmt.Println()

	// Open browser in background — don't fail if it errors.
	go openBrowser(url)

	srv := offline.NewHTTPServer(manifest, runner, port)
	if err := srv.Start(); err != nil {
		log.Fatalf("HTTP server error: %v", err)
	}
}

// runCLIMode runs the interactive terminal interface.
func runCLIMode(manifest *offline.BundleManifest, runner *offline.Runner) {
	offline.RunCLI(manifest, runner)
}

// detectMode returns "http" or "cli" based on the environment.
func detectMode() string {
	if runtime.GOOS == "windows" {
		return "http"
	}
	// Desktop Linux/macOS: use HTTP server.
	if os.Getenv("DISPLAY") != "" || os.Getenv("WAYLAND_DISPLAY") != "" {
		return "http"
	}
	if runtime.GOOS == "darwin" {
		return "http"
	}
	// Headless Linux (SSH): default to CLI.
	return "cli"
}

// openBrowser launches the system browser pointing to url.
func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		cmd = exec.Command("cmd", "/c", "start", url)
	case "darwin":
		cmd = exec.Command("open", url)
	default:
		// Try common Linux openers in order.
		for _, opener := range []string{"xdg-open", "sensible-browser", "firefox", "chromium"} {
			if _, err := exec.LookPath(opener); err == nil {
				cmd = exec.Command(opener, url)
				break
			}
		}
	}
	if cmd != nil {
		cmd.Start() //nolint:errcheck
	}
}

func printUsage() {
	fmt.Println(`ForensicHub Offline Agent

Usage:
  agent-offline [--http] [--cli]

Flags:
  --http   Force HTTP server mode (open browser at http://localhost:7474)
  --cli    Force interactive CLI mode (best for SSH/headless)

Auto-detection:
  Windows         → HTTP mode
  Linux + DISPLAY → HTTP mode
  Linux headless  → CLI mode (SSH-friendly)

Files required next to the binary:
  bundle.json     Tool manifest (generated by ForensicHub server)
  tools/          Directory containing pre-bundled tool archives
`)
}
