import { renderToStaticMarkup } from 'react-dom/server'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

// printMarkdownAsPdf renders a Markdown report to a print-optimised HTML page and
// opens the browser's print dialog so the operator saves it as a PDF. This keeps
// the reports dependency-free: the same react-markdown/remark-gfm used to render
// reports on screen produces the printable document, and the browser's native
// "Save as PDF" is the most reliable way to a real PDF file across platforms.
export function printMarkdownAsPdf(filename: string, markdown: string) {
  const body = renderToStaticMarkup(
    <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>,
  )
  openPrintWindow(filename, body)
}

// documentTitle drives both the print-dialog default filename and the PDF's
// title, so a saved report is named after its subject rather than "document".
function openPrintWindow(documentTitle: string, bodyHtml: string) {
  const win = window.open('', '_blank', 'width=900,height=1000')
  if (!win) {
    // Pop-up blocked — tell the caller's toast path by throwing.
    throw new Error('Pop-up blocked — allow pop-ups for this site to export a PDF')
  }
  win.document.open()
  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(documentTitle)}</title>
<style>
  @page { size: A4; margin: 18mm 16mm; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
    color: #111; line-height: 1.5; font-size: 12px; margin: 0;
  }
  h1 { font-size: 20px; margin: 0 0 4px; }
  h2 { font-size: 15px; margin: 18px 0 6px; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
  h3 { font-size: 13px; margin: 14px 0 4px; }
  p { margin: 6px 0; }
  ul { margin: 6px 0; padding-left: 20px; }
  li { margin: 2px 0; }
  code { font-family: "SF Mono", Consolas, Menlo, monospace; background: #f2f2f2; padding: 1px 4px; border-radius: 3px; font-size: 11px; }
  pre { background: #f6f8fa; padding: 10px; border-radius: 6px; overflow-x: auto; font-size: 11px; white-space: pre-wrap; word-break: break-all; }
  table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 10.5px; }
  th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; vertical-align: top; word-break: break-word; }
  th { background: #f0f0f0; font-weight: 600; }
  tr:nth-child(even) td { background: #fafafa; }
  /* Long monospace values (ids, hashes) must wrap, not overflow the page. */
  td { max-width: 220px; overflow-wrap: anywhere; }
  .ah-footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #eee; color: #888; font-size: 9px; }
  @media print { .ah-noprint { display: none; } }
</style>
</head>
<body>
${bodyHtml}
<div class="ah-footer">Generated by AnalysisHub · ${escapeHtml(new Date().toISOString())}</div>
<script>
  // Give the layout a tick to settle, then open the print dialog. onafterprint
  // closes the helper window whether the user saves or cancels.
  window.onload = function () { setTimeout(function () { window.focus(); window.print(); }, 150); };
  window.onafterprint = function () { window.close(); };
</script>
</body>
</html>`)
  win.document.close()
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string
  ))
}
